### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by pbrisbin** [freckle/haskell-tag-action#7]
Apparently `yq` can read JSON files just as easily as Yaml. This means one can run this action, completely as-is, to release a JavaScript project:

```yaml
- id: tag
  uses: haskell-tag-action@...
  with:
    package-yaml: ./package.json

- if: ${{ steps.tag.outputs.tag }}
  uses: whatever/npm-release-action 
```

I think we should make this a first class use-case and update naming to reflect this flexibility. We could also consider coding in the logic to find yaml-or-json by default, though that could make the, currently very trivial Action more complicated.
